### ISSUE TITLE
req: join csklub

### ISSUE THREAD

**Issue by profnandaa** [csklub/algorithms-in-js#7]
BTW we have an initiative called CSKlub, you can join and run this project from there with other members -- http://kazi.es/cs

**Comment by ezkemboi** [comment]
Sure @profnandaa, I think we can leave the issue open for now so that also other people can join the initiative.

**Comment by ezkemboi** [comment]
@profnandaa feel free to close this issue as I have fully transferred this repo to CSKlub.

**Comment by profnandaa** [comment]
Sounds great, thanks!
